---
layout: single
title: ""
resources: 
  - "images/html/md1_labs.html"
  - "images/html/lib"
---

# ManyDogs 1 Collaborators <br>
These research groups are registered collaborators in the [first ManyDogs](manydogs1) study and the Team Captains designated at each institution are responsible for organizing ManyDogs at their site. If you're interested in joining their teams or bringing your dog to participate in the study at one of these locations, we recommend contacting them directly to learn more about their site's sign-up and participation process.

* [Canine Cognition Center](https://sites.bc.edu/doglab/), _Boston College_ <br>
	<span style="color:#25679E;">Team Captains: Shennai Palermo & Anya Parks</span>
* [Brown Dog Lab](https://sites.brown.edu/browndoglab/), _Brown University_ <br>
	<span style="color:#25679E;">Team Captains: Daphna Buchsbaum & Madeline Pelgrim</span>
* [Canine Companions](https://canine.org/), _Canine Companions_ <br>
	<span style="color:#25679E;">Team Captain: Emily Bray</span>
* [Duke Canine Cognition Center](https://evolutionaryanthropology.duke.edu/research/dogs), _Duke University_ <br>
	<span style="color:#25679E;">Team Captain: Hannah Salomons</span>
* [The Family Dog Project](https://familydogproject.elte.hu/)	, _Eötvös Loránd University_ <br>
  <span style="color:#25679E;">Team Captain: Andrea Sommese</span>
* [Thinking Dog Center](https://sites.google.com/view/huntertdc/home), _Hunter College_ <br>
	<span style="color:#25679E;">Team Captain: Sarah Byosiere</span>
* [IWU Dog Scientists](https://www.iwudogscientists.com/), _Illinois Wesleyan University_ <br>
	<span style="color:#25679E;">Team Captain: Ellen Furlong</span>
* [Canid Behavior Research Group](https://www.canids.com.ar/), _National Scientific and Technical Research Council_ <br>
	<span style="color:#25679E;">Team Captain: Mariana Bentosela</span>
* [Social Cognition Lab](https://www.socialcognitionlab.com/), _Queen's University_<br>
	<span style="color:#25679E;">Team Captain: Valerie Kuhlmeier</span>
* [Pet Behaviour Consulting](https://www.unime.it/it/dipartimenti/vet), _Department of Veterinary Sciences, Università degli Studi di Messina_<br> 
	<span style="color:#25679E;">Team Captain: Daniela Alberghina</span>
* [Arizona Canine Cognition Center](https://dogs.arizona.edu/), _The University of Arizona_ <br>
	<span style="color:#25679E;">Team Captains: Emily Bray, Gitanjali Gnanadesikan, & Evan MacLean</span>
* [Animal Health and Welfare Centre](https://www.sparsholt.ac.uk/ucs-animal-zoo-management-facilities/), _University Centre Sparsholt_ <br>
	<span style="color:#25679E;">Team Captain: Marianne Freeman</span>
* Comparative Cognition Lab, _University of Manitoba_<br>
	<span style="color:#25679E;">Team Captain: Debbie Kelly</span>
* [Canine Cognition and Human Interaction Lab](https://dogcog.unl.edu), _University of Nebraska-Lincoln_ <br>
	<span style="color:#25679E;">Team Captain: Jeffrey Stevens</span>
* [Dog Cognition Centre](https://www.port.ac.uk/research/research-centres-and-groups/dog-cognition-centre), _University of Portsmouth_ <br>
	<span style="color:#25679E;">Team Captain: Jennifer Leighton</span>
* [Comparative Cognitive Science Lab](http://www.ccsl.uniri.hr/), _University of Rijeka_ <br>
	<span style="color:#25679E;">Team Captain: Ljerka Ostojić</span>
* [The Clever Dog Lab](https://www.vetmeduni.ac.at/cleverdoglab), _University of Veterinary Medicine Vienna_ <br>
	<span style="color:#25679E;">Team Captains: Ludwig Huber & Christoph Völter</span>
* Department of Psychology of Individual Differences, _University of Warsaw_ <br>
	<span style="color:#25679E;">Team Captains: Marta Golańska & Anna Reinholz</span>
* [Canine Cognition Center](https://doglab.yale.edu/), _Yale University_ <br>
	<span style="color:#25679E;">Team Captains: Daniel Horschler, Emily Richards, & Zachary Silver</span>

### Map of labs
<iframe height="400" width="600" src="images/html/md1_labs.html" title="Interactive map of labs" alt="Map of world with dots representing the location of each ManyDogs lab." style="border:none;"  data-external="1"></iframe>
Hover over dots to see lab names, and zoom and drag map to explore lab locations more closely.

# Many-X Collaborators
We're thrilled to partner with other multi-lab consortiums that promote open science practices and collaboration.

* [ManyBabies](https://manybabies.github.io/): Multi-lab replications of influential experiments in developmental psychology.
* [ManyPrimates](https://manyprimates.github.io): Establishing a culture of collaboration in primate cognition research.
