---
title: ""
---

* [Auburn Canine Performance Sciences](https://www.vetmed.auburn.edu/research/cps/), _Auburn University_ <br>
	<span style="color:#25679E;">Team Lead: Lucia Lazarowski</span>
* [Canine Cognition Center](https://sites.bc.edu/doglab/), _Boston College_ <br>
	<span style="color:#25679E;">Team Leads: Angie Johnston</span>
* [Brown Dog Lab](https://sites.brown.edu/browndoglab/), _Brown University_ <br>
	<span style="color:#25679E;">Team Leads: Daphna Buchsbaum</span>
* [Canine Companions](https://canine.org/), _Canine Companions_ <br>
	<span style="color:#25679E;">Team Lead: Emily Bray</span>
* [Duke Canine Cognition Center](https://evolutionaryanthropology.duke.edu/research/dogs), _Duke University_ <br>
	<span style="color:#25679E;">Team Lead: Brian Hare</span>
* [The Family Dog Project](https://familydogproject.elte.hu/)	, _Eötvös Loránd University_ <br>
  <span style="color:#25679E;">Team Lead: Andrea Sommese</span>
* [Thinking Dog Center](https://sites.google.com/view/huntertdc/home), _Hunter College_ <br>
	<span style="color:#25679E;">Team Lead: Sarah Byosiere</span>
* [Yamamoto Lab](https://sites.google.com/view/yamamotolabwrcias/), _Kyoto University Institute for Advanced Study_ <br>
	<span style="color:#25679E;">Team Lead: Hoi-Lam Jim</span>
* [Leader Dogs for the Blind](https://www.leaderdog.org/), _Leader Dogs for the Blind_ <br>
	<span style="color:#25679E;">Team Lead: Sarah Byosiere</span>
* [Canine Research Unit](https://play.psych.mun.ca/cru/), _Memorial University_ <br>
	<span style="color:#25679E;">Team Lead: Carolyn Walsh</span>
* [Canid Behavior Research Group](https://www.canids.com.ar/), _National Scientific and Technical Research Council_ <br>
	<span style="color:#25679E;">Team Lead: Mariana Bentosela</span>
* [Social Cognition Lab](https://www.socialcognitionlab.com/), _Queen's University_<br>
	<span style="color:#25679E;">Team Lead: Valerie Kuhlmeier</span>
* [Transylvania University](https://www.transy.edu/academics/faculty/efurlong/), _Transylvania University_ <br>
	<span style="color:#25679E;">Team Lead: Ellen Furlong</span>
* [Pet Behaviour Consulting](https://www.unime.it/it/dipartimenti/vet), _Department of Veterinary Sciences, Università degli Studi di Messina_<br> 
	<span style="color:#25679E;">Team Lead: Daniela Alberghina</span>
* [Arizona Canine Cognition Center](https://dogs.arizona.edu/), _The University of Arizona_ <br>
	<span style="color:#25679E;">Team Lead: Evan MacLean</span>
* [Animal Health and Welfare Centre](https://www.sparsholt.ac.uk/ucs-animal-zoo-management-facilities/), _University Centre Sparsholt_ <br>
	<span style="color:#25679E;">Team Lead: Marianne Freeman</span>
* Comparative Cognition Lab, _University of Manitoba_<br>
	<span style="color:#25679E;">Team Lead: Debbie Kelly</span>
* [Canine Cognition and Human Interaction Lab](https://dogcog.unl.edu), _University of Nebraska-Lincoln_ <br>
	<span style="color:#25679E;">Team Lead: Jeffrey Stevens</span>
* [Dog Cognition Centre](https://www.port.ac.uk/research/research-centres-and-groups/dog-cognition-centre), _University of Portsmouth_ <br>
	<span style="color:#25679E;">Team Lead: Jennifer Leighton</span>
* [Comparative Cognitive Science Lab](http://www.ccsl.uniri.hr/), _University of Rijeka_ <br>
	<span style="color:#25679E;">Team Lead: Ljerka Ostojić</span>
* [The Clever Dog Lab](https://www.vetmeduni.ac.at/cleverdoglab), _University of Veterinary Medicine Vienna_ <br>
	<span style="color:#25679E;">Team Leads: Ludwig Huber & Christoph Völter</span>
* Department of Psychology of Individual Differences, _University of Warsaw_ <br>
	<span style="color:#25679E;">Team Leads: Marta Golańska & Anna Reinholz</span>
* [Canine Cognition Center](https://doglab.yale.edu/), _Yale University_ <br>
	<span style="color:#25679E;">Team Leads: Laurie Santos</span>
