---
title: ""
---

# Donate to ManyDogs

Are you looking to help us achieve our mission of fostering global collaboration and open science practices through multi-site canine science projects? Well, you can now contribute to our endeavor!

ManyDogs is a part of the [Open Source Collective](https://opencollective.com/opensource), a registered non-profit organization that helps open science/source projects like us maintain their finances. Anyone can contribute funds to our account (please note that 10% will be deducted by Open Source Collective to fund their services), and we will be able to use those funds for our project. All income and payments are publicly posted to keep our finances transparent.

If you would like to support ManyDogs, please find out more at <https://opencollective.com/manydogs> or [email us](mailto::manydogsproject@gmail.com). 




![Photo by <a href="https://unsplash.com/@juliablumberg?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Julia Blumberg</a> on <a href="https://unsplash.com/photos/a-group-of-small-dogs-standing-next-to-each-other-3sprpHekiRU?utm_content=creditCopyText&utm_medium=referral&utm_source=unsplash">Unsplash</a>](images/julia-blumberg-3sprpHekiRU-unsplash_cropped.jpg)
      