---
layout: single
title: ""
permalink: /getinvolved/
# author_profile: true

---

# Get Involved in ManyDogs

There are multiple ways that you can get involved in ManyDogs, and contributors at all stages of their careers (Undergraduate to Professor Emeritus) are very welcome to join the project.

## The Overall Project

The ManyDogs Project is a large group of researchers who hope to conduct a number of studies over the next several years. If you're interested in becoming a member of the ManyDogs project and helping out with behavioral data collection,  administration,  and/or creative roles, please complete the [Member Registration Form](https://forms.gle/nERgQYgAWTDgAza67). If you're not able to help with the research we're conducting but are interested in what we're working on, check out our [publications](publications.html).<!--If you want to participate in a particular study, (e.g., ManyDogs 1), no need to complete the Member Registration Form---just skip down to the Contributor Sign-Up Survey below for the study you're interested in.-->

## ManyDogs Projects

[ManyDogs 1](manydogs1.qmd) has completed, and the manuscript with the main experimental results is in press at _Animal Behavior and Cognition_. But we are soliciting ideas for the next project. If you have a great project idea, check out the [call for project ideas](call.qmd).<!--Check back later for updates on the project.If your research site would like to register for data collection, please read the [Manual](https://docs.google.com/document/d/1iuYElQSssoOMVC3nu7BLrFZovoM0TIEqmGM1bUaYbpo/edit?usp=sharing) and prereview the [questions](https://drive.google.com/file/d/1xgxU9X5KeUAAPcUl5dB8LfgPjO55p3Ea/view?usp=sharing) you will need to answer before registering through our [Contributor Sign-Up Survey](https://bit.ly/md1contributor) - this will ensure you have all the required information available to sign up your research site.

If you would like to get involved but do not have a site for behavioural data collection, please get in touch anyway! There are administrative, funding acquisition, and creative roles within ManyDogs that can lead to authorship on this or subsequent studies.  -->

<!--If you are a dog owner who wants to participate in ManyDogs 1 with your dog, check out our [Collaborators](/manydogs1.qmd#manydogs-1-collaborators) for a complete list of the locations where ManyDogs 1 is being offered. If there's a location near you, we recommend that you reach out to them for details on how to sign up for their research program.-->

<!-- ## Join Our Communication Network -->

<!-- To receive periodic project updates, researchers can join our [**GoogleGroup**](https://groups.google.com/u/2/g/manydogs) (i.e., email list). For more frequent communication, researchers can join our [**Slack Workspace**](https://manydogsproject.slack.com), where much of our day-to-day discussion takes place. To join Slack, please [email](mailto:manydogsproject@gmail.com) the project coordinators specifying the email address that you would like to have invited. We'll also be posting important dates and announcements about the project via [Twitter](https://www.twitter.com/manydogsproject) or [Mastodon](https://fediscience.org/@ManyDogs), give us a follow!  -->

## Other Big Team Science Groups
We're thrilled to partner with other big team science, multi-lab consortiums that promote open science practices and collaboration. If you're not able to get involved in ManyDogs, feel free to check out other big team science groups.

* [ManyBabies](https://manybabies.github.io/)
* [ManyBirds](https://themanybirds.com/)
* ManyFishes
* [ManyGoats](https://www.themanygoatsproject.com/)
* [ManyManys](https://manymanys.github.io/)
* [ManyPrimates](https://manyprimates.github.io)
* ManyZoos
* [Psychological Science Accelerator](https://psysciacc.org/)