---
title: ""
---

# Publications

## 2024

ManyDogs Project, Espinosa, J., Hare, E., Alberghina, D., Valverde, B. M. P., & Stevens, J. R. (2024). Data from ManyDogs 1. _Journal of Open Psychology Data_, 12(1). [doi:10.5334/jopd.109](https://doi.org/10.5334/jopd.109)

[PDF](https://doi.org/10.5334/jopd.109) • [Preprint](https://doi.org/10.31219/osf.io/jw24a) • [Data and code](https://osf.io/7rwpc/)

* This article publishes all of the data for the ManyDogs 1 project, along with a codebook and a description of how the data were collected.


## 2023

ManyDogs Project, Alberghina, D., Bray, E., Buchsbaum, D., Byosiere, S.-E., Espinosa, J., Gnanadesikan, G., Guran, C.-N.A., Hare, E., Horschler, D., Huber, L., Kuhlmeier, V.A., MacLean, E., Pelgrim, M.H., Perez, B., Ravid-Schurr, D., Rothkoff, L., Sexton, C., Silver, Z., & Stevens, J.R. (2023). ManyDogs Project: A big team science approach to investigating canine behavior and cognition. _Comparative Cognition and Behavior Reviews_, 18, 59-77. 
[doi:10.3819/CCBR.2023.180004](https://doi.org/10.3819/CCBR.2023.180004)

[PDF](https://doi.org/10.3819/CCBR.2023.180004) • [Preprint](https://doi.org/10.31234/osf.io/j82uc)

* This article introduces the ManyDogs Project by discussing the importance of studying canine behavioral science, situating ManyDogs among other examples of large-scale canine science, and describing the core aims of the ManyDogs Project.

ManyDogs Project, Espinosa, J., Stevens, J.R., Alberghina, D., Alway, H.E.E., Barela, J.D., Bogese, M., Bray, E.E., Buchsbaum, D. Byosiere, S.-E., Byrne, M., Cavalli, C. M., Chaudoir, L. M., Collins-Pisano, C., DeBoer, H.J., Douglas L.E.L.C., Dror, S., Dzik, M.V., Ferguson, B., Fisher, L., Fitzpatrick, H.C., Freeman, M.S., Frinton, S.N., Glover, M.K., Gnanadesikan, G.E., Goacher, J.E.P., Golańska, M., Guran, C.-N.A., Hare, E., Hare, B. Hickey, M., Horschler, D.J., Huber, L., Jim, H.-L., Johnston, A.M., Kaminski, J. Kelly, D.M., Kuhlmeier, V.A., Lassiter, L., Lazarowski, L., Leighton-Birch, J., MacLean, E.L., Maliszewska, K., Marra, V., Montgomery, L.I., Murray, M.S., Nelson, E.K., Ostojić, L., Palermo, S.G., Parks Russell, A.E., Pelgrim, M.H., Pellowe, S.D., Reinholz, A., Rial, L.A., Richards, E.M., Ross, M.A., Rothkoff, L.G., Salomons, H., Sanger, J.K., Santos, L., Shirle, A.R., Shearer, S.J., Silver, Z.A., Silverman, J.M., Sommese, A., Srdoc, T., St. John-Mosse, H., Vega, A.C., Vékony, K., Völter, C.J., Walsh C.J., Worth, Y.A., Zipperling, L.M.I., Żołędziewska, B., & Zylberfuden, S.G. (2023). ManyDogs 1: A multi-lab replication study of dogs’ pointing comprehension. _Animal Behavior & Cognition_, 10(3), 232-286. [doi:10.26451/abc.10.03.03.2023](https://doi.org/10.26451/abc.10.03.03.2023)

[PDF](https://doi.org/10.26451/abc.10.03.03.2023) • [Preprint](https://doi.org/10.31234/osf.io/4kncr) • [Stage 1 registred report](https://doi.org/10.31234/osf.io/f86jq) • [Data and code](https://osf.io/9r5xf/)

* This article describes [ManyDogs 1](manydogs1.html), the first empirical study to come out of the ManyDogs Project that evaluates domestic dogs’ understanding of a common human gesture, the point.

<!-- ## In press -->


# Presentations

## Talks and panels

ManyDogs Project & Espinosa, J. (2023). Exploring variability in dogs’ responses to human pointing. Comparative Cognition Conference, Melbourne, Florida, USA.

Sommese, A. (2023). ManyDogs 1: A multi-lab replication study of dogs' pointing comprehension. [Canine Science Forum](https://csf2023.elte.hu/), Budapest, Hungary.

Espinosa, J. (2022). Big team science in comparative cognition. Comparative Cognition Conference, Melbourne, Florida, USA.

ManyDogs Project, Espinosa, J., Byosiere, S.-E., Pelgrim M. (2021). ManyDogs Project. [Canine Science Forum](https://csf2021.psianimal.pt/), virtual meeting.

Stevens, J.R. (2021). The ManyDogs Project: A big team science approach to canine cognition, International Society for Anthrozoology, virtual meeting.


## Posters and social media conferences (* presenters)

Gerwisch, K.*, Mackie, L., Folkertsma, R., ManyDogs Project, Huber, L. (2025). Overimitation in assistance and family dogs: The influence of the human-dog relationship quality. Canine Science Forum, Budapest, Hungary.

Jim, H.-L.*, Song, X., Kuroshima, H., Yamamoto, S., Gerwisch, K., Mackie, L., & ManyDogs Project (2025). ManyDogs 2: Investigating overimitation in dogs. [85th Annual Meeting of the Japanese Society of Animal Psychology](https://sites.google.com/hatapsydoshisha.com/jsap2025), Kyoto, Japan.

ManyDogs Project, Gerwisch, K.*, Mackie, L., Huber, L. (2025). Investigating Overimitation in Dogs:
 The ManyDogs 2 Project. [Big Team Science Conference](https://bigteamscienceconference.github.io/), online.

Bray, E.E.* (2023). ManyDogs Project: Leveraging big team science to understand canine behavior and cognition. [Animal Behaviour Twitter Conference](https://twitter.com/search?q=%23AnimBehav2023&src=typed_query&f=top).

Collins-Pisano, C., Montgomery, L., Elrod, L., Lazarowski, L., & Katz, J. (2023).  Dogs’ performance on an object-choice task utilizing a momentary contralateral point. Comparative Cognition Conference, Melbourne, Florida, USA.

Srdoc, T., Ostojić, L., & ManyDogs Project (2023). ManyDogs 1: A multi-lab replication study of dogs' pointing comprehension. [Behavior 2023](https://www.uni-bielefeld.de/fakultaeten/biologie/forschung/veranstaltungen/behaviour2023/), Bielefeld, Germany.

Barela, J.*, Wolff, L., & Stevens, J.R. (2022). The ManyDogs Project: A team science approach to canine cognition. [Nebraska Symposium on Motivation: Canine Cognition and the Human Bond](https://motivation.unl.edu/previous-symposia/), Lincoln, Nebraska, USA.

Gnanadesikan, G. & Espinosa, J. (2021). ManyDogs 1: An international collaborative approach to pointing comprehension in domestic dogs. [Animal Behaviour Twitter Conference](https://twitter.com/search?q=%23AnimBehav2021&src=typed_query&f=top), online.


# Newsletters

[March 2024](assets/ManyDogs_Newsletter_1_2024-03.pdf)
